### ISSUE TITLE
Map preview shouldn't restart

### ISSUE THREAD

**Issue by t83714** [magda-io/magda-preview-map#24]
**Describe the bug**

```
TypeError: Cannot read property 'toLowerCase' of null
    at proxyAllowedHost (/usr/src/app/component/node_modules/terriajs-server/lib/controllers/proxy.js:93:21)
    at Request.followRedirect (/usr/src/app/component/node_modules/terriajs-server/lib/controllers/proxy.js:236:37)
    at Redirect.onResponse (/usr/src/app/component/node_modules/request/lib/redirect.js:84:42)
    at Request.onRequestResponse (/usr/src/app/component/node_modules/request/request.js:986:22)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by t83714** [comment]
close as we've upgraded to newer version: https://github.com/magda-io/magda-preview-map/issues/28
